# Generated by Django 4.2.5 on 2023-09-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': "Member's"},
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Mother', 'mother'), ('Father', 'father'), ('Husband', 'husband'), ('Wife', 'wife'), ('Son', 'son'), ('DaughterInLaw', 'daughterinlaw'), ('Brother', 'brother'), ('SisterInLaw', 'sisterinlaw')], max_length=25)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relationship', to='first_app.member')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relationship', to='first_app.member')),
            ],
        ),
    ]
